version: '3.7'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SQLSecure?
    volumes:
      - local-dev-sql:/var/opt/mssql

volumes:
  local-dev-sql: